[alias]
b = "build"
br = "build --release"
c = "check"
cl = "clippy --workspace"
t = "test --workspace"
r = "run"
rr = "run --release"
w = "watch -x check"
wr = "watch -x run"
wa = "watch -x 'check --workspace'"

[build]
jobs = 4

[term]
color = "always"

