[package]
name = "ccutil"
default-run = "ccutil"
description = "CLI for ccutils devtools"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
authors = { workspace = true }
categories = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
keywords = { workspace = true }

[dependencies]

[lints]
workspace = true
